### ISSUE TITLE
The flavors of generators are not documented

### ISSUE THREAD

**Issue by vporton** [research-ag/prng#4]
It is unclear from https://github.com/research-ag/prng/blob/main/README.md how to use some generators:

The documented generators are SFC64, SFC32 but the example code uses `Prng.SFCa()` (not `SFC32` or `SFC64`). It is even unclear from the docs whether `SFCa()` is 32-bit or 64-bit.

Also need to document arguments of constructors.

**Comment by timohanke** [comment]
Thanks for pointing this out. Fixed in #6.
